### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by cwd-k2** [wantJoy1/wa#1]
現状 .gitignore が無いようなので追加したほうが良さげ
この辺参考にするとか
https://github.com/github/gitignore/blob/master/Rust.gitignore
bin だから `Cargo.lock` は ignore しない形？

**Comment by wantJoy1** [comment]
特に理由はないので、.gitignoreを追加した

**Comment by cwd-k2** [comment]
ア，どっちかというと
```
debug/
target/
```
を `gitignore` に書く感じだと思う
